from converter_for_test_gesign.case import Case, Step
from converter_for_test_gesign.convert_cases_to_code import convert_cases_to_code


def test_convert_one_case():
    cases = list()
    case = Case("Тест", feature="Раздел 1", story="Бизнес-кейс 1.1", method="test_one")
    step = Step("Шаг 01")
    case.steps.append(step)
    step = Step("Шаг 02")
    step.add_comment("Первый комментарий")
    step.add_comment("Второй комментарий")
    case.steps.append(step)
    cases.append(case)
    case = Case("Второй тест", feature="Раздел 1", story="Бизнес-кейс 1.1", method="test_two")
    case.steps.append(Step("Шаг 01 (во втором тесте)"))
    cases.append(case)
    case = Case("Тест без шагов", feature="Раздел 1", story="Бизнес-кейс 1.1", method="test_without_steps")
    case.add_comment("В этом тесте нет ни одного шага")
    cases.append(case)

    s = list()
    s.append("")
    s.append("")
    s.append("@allure.feature('Раздел 1')")
    s.append("@allure.story('Бизнес-кейс 1.1')")
    s.append("@allure.title('Тест')")
    s.append("def test_one(app):")
    s.append("")
    s.append("    with allure.step('Шаг 01'):")
    s.append("        pass")
    s.append("")
    s.append("    with allure.step('Шаг 02'):")
    s.append("        # Первый комментарий")
    s.append("        # Второй комментарий")
    s.append("        pass")
    s.append("")
    s.append("")
    s.append("@allure.feature('Раздел 1')")
    s.append("@allure.story('Бизнес-кейс 1.1')")
    s.append("@allure.title('Второй тест')")
    s.append("def test_two(app):")
    s.append("")
    s.append("    with allure.step('Шаг 01 (во втором тесте)'):")
    s.append("        pass")
    s.append("")
    s.append("")
    s.append("@allure.feature('Раздел 1')")
    s.append("@allure.story('Бизнес-кейс 1.1')")
    s.append("@allure.title('Тест без шагов')")
    s.append("def test_without_steps(app):")
    s.append("    pass")
    s.append("")

    lines = convert_cases_to_code(cases)
    assert s == lines
